package org.web.prueba;

// Generated 05/09/2014 17:49:27 by Hibernate Tools 4.0.0

/**
 * PedidoArticuloId generated by hbm2java
 */
public class PedidoArticuloId implements java.io.Serializable {

	private int idped;
	private int idart;

	public PedidoArticuloId() {
	}

	public PedidoArticuloId(int idped, int idart) {
		this.idped = idped;
		this.idart = idart;
	}

	public int getIdped() {
		return this.idped;
	}

	public void setIdped(int idped) {
		this.idped = idped;
	}

	public int getIdart() {
		return this.idart;
	}

	public void setIdart(int idart) {
		this.idart = idart;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PedidoArticuloId))
			return false;
		PedidoArticuloId castOther = (PedidoArticuloId) other;

		return (this.getIdped() == castOther.getIdped())
				&& (this.getIdart() == castOther.getIdart());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdped();
		result = 37 * result + this.getIdart();
		return result;
	}

}
