package org.web.prueba;

// Generated 05/09/2014 17:49:27 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private Integer idped;
	private ClienteOrganizacion clienteOrganizacion;
	private Date fret;
	private Date fdev;
	private Set pedidoArticulos = new HashSet(0);

	public Pedido() {
	}

	public Pedido(ClienteOrganizacion clienteOrganizacion, Date fret, Date fdev) {
		this.clienteOrganizacion = clienteOrganizacion;
		this.fret = fret;
		this.fdev = fdev;
	}

	public Pedido(ClienteOrganizacion clienteOrganizacion, Date fret,
			Date fdev, Set pedidoArticulos) {
		this.clienteOrganizacion = clienteOrganizacion;
		this.fret = fret;
		this.fdev = fdev;
		this.pedidoArticulos = pedidoArticulos;
	}

	public Integer getIdped() {
		return this.idped;
	}

	public void setIdped(Integer idped) {
		this.idped = idped;
	}

	public ClienteOrganizacion getClienteOrganizacion() {
		return this.clienteOrganizacion;
	}

	public void setClienteOrganizacion(ClienteOrganizacion clienteOrganizacion) {
		this.clienteOrganizacion = clienteOrganizacion;
	}

	public Date getFret() {
		return this.fret;
	}

	public void setFret(Date fret) {
		this.fret = fret;
	}

	public Date getFdev() {
		return this.fdev;
	}

	public void setFdev(Date fdev) {
		this.fdev = fdev;
	}

	public Set getPedidoArticulos() {
		return this.pedidoArticulos;
	}

	public void setPedidoArticulos(Set pedidoArticulos) {
		this.pedidoArticulos = pedidoArticulos;
	}

}
